### ISSUE TITLE
Don't require output variables in household definitions

### ISSUE THREAD

**Issue by nikhilwoodruff** [PolicyEngine/policyengine-api#468] opened 2023-05-27 17:46 UTC

**Comment by MaxGhenis** [comment] 2023-05-27 19:28
Is this a duplicate of https://github.com/PolicyEngine/policyengine-api/issues/230?

**Comment by MaxGhenis** [comment] 2023-07-13 13:18
Closing as I think it is

**Closed by MaxGhenis** 2023-07-13 13:18 UTC
