### ISSUE TITLE
500 server error when computing UK reform impact

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine-api#11] opened 2022-12-10 08:21 UTC
https://beta.policyengine.org/uk/policy?reform=23&focus=policyOutput.netIncome&region=uk&timePeriod=2022&baseline=1

>We ran into an issue when trying to simulate your policy. Please try again later. The full message is "Error computing reform impact: <!doctype html>\n<html lang=en>\n<title>500 Internal Server Error</title>\n<h1>Internal Server Error</h1>\n<p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>\n"

This reform changes the blind TV license discount

**Comment by nikhilwoodruff** [comment] 2022-12-10 17:01
Fixed now - I think the root cause was that the default baseline policy (# 2) got removed

**Closed by nikhilwoodruff** 2022-12-10 17:01 UTC
Labels: bug

**Comment by MaxGhenis** [comment] 2022-12-10 17:03
Thanks - for posterity could you describe how you fixed it? Did you reset the database?

**Comment by nikhilwoodruff** [comment] 2022-12-10 18:37
Yeah, basically every time the initialisation of the API involves adding the baseline policies # 1 (UK baseline) and # 2 (US baseline) if they don't exist, skipping if they do. For some reason the UK baseline already existed (expected) but the US baseline didn't (not expected). But since the UK baseline was already in there, the command skipped the rest. This broke the compute API because we asked for economic comparisons between a policy and # 2 (which didn't exist).

I fixed this by making sure that # 1 and # 2 are attempted-added separately.
