### ISSUE TITLE
Household scenarios calculate for 2023, even when 2024 is selected

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine-api#1792] opened 2024-09-16 18:00 UTC
For example, this household shows $32,681 net income for 2024 in the web app: https://policyengine.org/us/household?focus=householdOutput.pythonReproducibility&household=47266

But [this notebook](https://colab.research.google.com/drive/1S7-jyQiqWhR49qIfXb3wcisU34jcIYAG?authuser=0#scrollTo=VBbW8XDL86ji) shows it should be $33,063. The 2023 value ($32,077) isn't quite right either, but we've compared some individual programs to find that they match 2023 policy.

**Comment by anth-volk** [comment] 2024-09-16 19:35
Do we have any idea at this point if the policy calculator also calculates over 2023?

**Comment by MaxGhenis** [comment] 2024-09-16 20:09
The microsim part of the app uses the year appropriately. I don't know about the household reform part.

**Comment by anth-volk** [comment] 2024-09-19 18:20
Check this out, too. Here's the varying your net income chart:

<img width="1440" alt="Screen Shot 2024-09-19 at 8 19 05 PM" src="https://github.com/user-attachments/assets/ca8293e9-4bfb-4b9f-ae5c-8be2543da41b">

The line sits at $32,808, which is closer to the Colab's output just over $33k, but still not correct, and the dot also isn't correct.

**Comment by anth-volk** [comment] 2024-11-04 20:52
Similar issue present for this policy: https://policyengine.org/us/household?focus=householdOutput.earnings&reform=69001&region=ut&timePeriod=2026&baseline=2&household=49302

**Comment by anth-volk** [comment] 2024-11-08 18:17
Interestingly, the linked Colab notebook actually now shows $32,681 as the 2024 net income for this household. I don't know why or what that means for this issue, as the line is still off by $127, but just wanted to post that update.

**Comment by anth-volk** [comment] 2024-11-08 23:31
Closing the line/value mismatch as duplicate of https://github.com/PolicyEngine/policyengine-us/issues/5317. The discrepancies in the California YCTC are open as https://github.com/PolicyEngine/policyengine-us/issues/5316.

**Closed by anth-volk** 2024-11-08 23:31 UTC
Labels: bug
